overwrite: true
schema: ${GRAPHQL_SCHEMA_URL:http://localhost:3000/graphql}
documents:
    - 'src/**/*.{ts,tsx}'
    - '!src/graphql/*'
generates:
    src/graphql/index.tsx:
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - fragment-matcher
        config:
            avoidOptionals: true
            scalars:
                NaiveDateTime: string
                DateTime: string
                Date: string
            withComponent: false
            withHOC: false
            withHooks: true
